### PR TITLE
Utf8 support

### PR DESCRIPTION
**Pull request by c9s**
This is a WIP PR

See also: http://www.cprogramming.com/tutorial/unicode.html

Related issue: #35 #14

### CODE REVIEW

**Comment by c9s** [comment]
Good news! the utf8 test cases are passed! @sqmk

**Comment by arnested** [comment]
:+1:

**Comment by sqmk** [comment]
Looking good. Merging and I'll tag and release v2.0.0 via PECL.

**Comment by sqmk** [comment]
Might be helpful if I merged the PR before closing this :-P

**Comment by osopolar** [comment]
Coming from an issue in a drupal contrib module (https://www.drupal.org/node/2566311), I can confirm that this solves the issue. Thanks c9s for your great job and sqmk for the new release.

**Comment by osopolar** [comment]
@c9s Could the UTF8 implementation be responsible for some illegal characters at the end of the minified string (see issue #46)?

**Pull request merged**
